### ISSUE TITLE
Not sure whehter it is working...

### ISSUE THREAD

**Issue by 9littlebees** [GMonlineua/Household_Dice_FVTT#1]
I've got this installed (v1.2) and activated in Foundry v11.315 but I'm not sure what it is supposed to be doing... There are no skins for Dice So Nice and the chat output is showing dice with pips rather than icons, which is what I was expecting. You also don't give any information about what this module does here on the GitHub, which would be really helpful for people who are installing Household and stumble across your module. So what does this module do?

**Comment by GMonlineua** [comment]
Hello, it was just a quick module for my game Household, so I didn't bother describing it much
I've just updated the README a little bit to make it clear how it should look like
I don't use Dice So Nice, so I think it doesn't work with it

Can you open console in developer tools, roll dice and see if there are any errors?

**Comment by 9littlebees** [comment]
I see it now, sorry for the bother!
